version: '2'
networks:
  sparkler_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.200.0.0/24
        gateway: 172.200.0.1

services:
    firefox:
      image: "selenium/standalone-firefox-debug"
      ports:
        - "4444:4444"
        - "9559:5900"
      networks:
        sparkler_net:
          ipv4_address: 172.200.0.2
    sparkler:
      image: sparkler
      ports:
        - "8983:8983"
      networks:
        sparkler_net:
          ipv4_address: 172.200.0.3
    domain-discovery:
      image: "domain-discovery"
      ports:
        - "5000:5000"
      networks:
        sparkler_net:
          ipv4_address: 172.200.0.4
