version: '2'
networks:
  sparkler_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.200.0.0/24
        gateway: 172.200.0.1

services:
    firefox:
      image: "selenium/standalone-firefox-debug"
      ports:
        - "4444:4444"
        - "9559:5900"
      networks:
        sparkler_net:
          ipv4_address: 172.200.0.2
    sparkler:
      image: "sujenshah/sce-sparkler"
      ports:
        - "8983:8983"
        - "6000:6000"
      volumes:
        - ../data/solr/crawldb/data:/data/solr/server/solr/crawldb/data
        - ../data/crawl-segments:/data/crawl-segments
        - ../data/dumper/dump:/data/sparkler/dump
        - ../logs/:/data/logs
        - ../sce-cmd/webui:/data/webui
      networks:
        sparkler_net:
          ipv4_address: 172.200.0.3
    domain-discovery:
      image: "sujenshah/sce-domain-explorer"
      ports:
        - "5000:5000"
      volumes:
        - ../data/dumper:/projects/sce/data/dumper
      environment:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      networks:
        sparkler_net:
          ipv4_address: 172.200.0.4
